language: node_js
sudo: required
node_js:
- stable
install:
- npm install
notifications:
  slack:
    on_success: always
    on_failure: always
    secure: rtd3uJ9XIhY7Iv2/FY8/pM+SA1YnJM74fhKeYzuXEc8otqX+BOiihsJSDS0lLrVO6MzIXErX86Sg3iotkH4iVQGvYEd0tGHGdEyxofG8tMQpNM802epXEJh7jcy5CxaCgnwGiLWbdDzSMg6Ahg8hxcG0g2HfomEfPGB03blilgpYk/zlEzhBlYBPHi988cBHVKQF40dvS/3I2hmkWGTkMQkh0GTUX2BPohGWTLYeF62dK5oonmvgrU8qEKuMye6vga6Yb/cAc77nu7yq5u+WxR29kFE6VVVHkt3o7vKabPs37fIO49d9QOaobG9dYThFOwe4PHNmfU3hnoM7Of97WXx/6NWFYKUGrG9Wvi0vgkhJ8u+2ehaADlACAZ3qe+eRL0GbzCyOm0ZExhyAJbfFHYB9z42lIZt9d36D41fNRAqroUgIlbAmwNY8tRMnbbKHNNNrFFhYY35JQ0nX0Dc5pDw0kvmbM5Zzrw7wU+KHgoCBupZz/Ewx7dr6sTPFKIoTH1fpnq/2sG6zIM1oVGWBsoYD4bbaacRVIjm2sJUS8qYnzCMLd57b5yDfhtrc6btad6M2lmpNOCl8aF9bmaeDsgXKgwcUflvntps0cx13bogfsmb12Qp3obxJXxjtej7Lx/cEDa/0ZouQKt0NP3voy3BLx0S7VY/PcPCyGcDT994=
deploy:
  skip_cleanup: true
  provider: heroku
  on: master
  app: damp-oasis-51013
  api_key:
    secure: V8kvt4Dr4LwIsGYmVaiX7vAqSC30UVAIya4nO8eVA9gY6pH3Gjg2iUrUSJ9XQmRXRnHQbumYjMcmnb2/F3WAdu4OvMYiQQ0FONz9w+QEBfoGFVTnVtA+l+QuF4wp3evrBD0laa3T4bj1/3tJtyvY0dqMBVu9iWmvPmte541TpDgSkIzY69BYtfoF3fJNDp8GyNXRAjAaCf6J0qCDm+cLjE6fB6WBKsO3NVG98Frs/jZ6oZfMHIGEL/7MsZmR65MrqHC3QMt0S+4iZCBtcN38TdzaymUy0DlL8ngNURS6Cd/kZoFwqYpWu/7qcmsBhsrPFav/Fi1Z1X8lpiE7+J4m3FUVgf1SrhyotpItTJf1NKyDoGaJSXXn1tjH43h3MBAHnCclDtFosPMuUwh8I2e4/mH2EZS+22ozxgpVJcYmixwH/Sn82nTyIokcMLhGd7YIBn/5WKKx+wKrnfPdZSFd7MMCC8PVUoGIUqEh5dmmIeunU1nuRQZ2NBF6wyw7FIJOVfO6cIgs8FSjirHYNbPe3JmoxFxm4/WvMpS/rihMN4R1TFakaLxjJbszsoQhq+vvKc9dR4MIMNTYUXdMpbbNVEPMRI6BIkTj2TrZnkMdTThEw19xBZ3xKoHgDWXtnkrkSuDtP2nyTitIvNE+7gNOnpzAEbU7WtfdCTvnL7VQMqs=
